export default {
  intro: '用户界面框架 (UI Frameworks)，对于 MVVP 的具体实现。',
  list: [
    {
      href: 'https://github.com/facebook/react',
      name: 'React',
      logo: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K',
      des: 'A JavaScript library for building user interfaces.',
      contributors: 1562,
      stars: '192k',
      score: { pop: 100, qua: 80, eco: 90 },
      comment: '评价',
    },
    {
      href: 'https://github.com/vuejs/core',
      name: 'Vue.js 3',
      logo: 'https://bestofjs.org/logos/vue.dark.svg',
      des: 'An approachable, performant and versatile framework for building web user interfaces.',
      contributors: 341,
      stars: '31.6k',
      score: { pop: 90, qua: 90, eco: 70 },
      comment: '评价',
    },
    {
      href: 'https://github.com/angular/angular',
      name: 'Angular',
      logo: 'https://raw.githubusercontent.com/angular/angular/main/aio/src/assets/images/logos/angular/angular.png',
      des: 'Angular is a development platform for building mobile and desktop web applications using Typescript/JavaScript and other languages.An approachable, performant and versatile framework for building web user interfaces.',
      contributors: 1593,
      stars: '82.9k',
      score: { pop: 80, qua: 90, eco: 60 },
    },
    {
      href: 'https://github.com/sveltejs/svelte',
      name: 'Svelte',
      logo: 'https://bestofjs.org/logos/svelte.dark.svg',
      des: 'Cybernetically enhanced web apps',
      contributors: 513,
      stars: '61k',
      score: { pop: 60, qua: 80, eco: 40 },
    },
    {
      href: 'https://github.com/vuejs/core',
      name: 'Solid',
      logo: 'https://www.solidjs.com/assets/logo.123b04bc.svg',
      des: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
      contributors: 113,
      stars: '20.7k',
      score: { pop: 40, qua: 80, eco: 40 },
    },
  ],
};
